dropped_columns:
- policy_number
- policy_bind_date
- policy_state
- policy_csl
- insured_zip
- insured_occupation
- incident_date
- insured_education_level
- insured_relationship
- injury_claim
- property_claim
- vehicle_claim
- incident_state
- incident_city
- incident_location
- auto_model
- auto_make
- auto_year
- _c39
renamed_columns:
  capital-gains: capital_gains
  capital-loss: capital_loss
target: fraud_reported
predictors:
- months_as_customer
- age
- policy_deductable
- policy_annual_premium
- umbrella_limit
- insured_sex
- insured_hobbies
- capital_gains
- capital_loss
- incident_type
- collision_type
- incident_severity
- authorities_contacted
- incident_hour_of_the_day
- number_of_vehicles_involved
- property_damage
- bodily_injuries
- witnesses
- police_report_available
- total_claim_amount
missing_predictors:
- collision_type
- property_damage
- police_report_available
numerical_predictors:
- months_as_customer
- age
- policy_deductable
- policy_annual_premium
- umbrella_limit
- capital_gains
- capital_loss
- incident_hour_of_the_day
- number_of_vehicles_involved
- bodily_injuries
- witnesses
- total_claim_amount
discrete_predictors:
- policy_deductable
- umbrella_limit
- incident_hour_of_the_day
- number_of_vehicles_involved
- bodily_injuries
- witnesses
continuous_predictors:
- months_as_customer
- age
- policy_annual_premium
- capital_gains
- capital_loss
- total_claim_amount
categorical_predictors:
- insured_sex
- insured_hobbies
- incident_type
- collision_type
- incident_severity
- authorities_contacted
- property_damage
- police_report_available
- policy_deductable_groups
- age_groups
- policy_annual_premium_groups
- months_as_customer_groups
ordinal_predictors:
- incident_severity
- policy_annual_premium_groups
- policy_deductable_groups
nominal_predictors:
- insured_sex
- insured_hobbies
- incident_type
- collision_type
- authorities_contacted
- property_damage
- police_report_available
- age_groups
- months_as_customer_groups
features_selected:
- bodily_injuries
- capital_gains
- capital_loss
- incident_hour_of_the_day
- incident_severity
- insured_hobbies_chess
- insured_hobbies_cross-fit
- insured_hobbies_others
- policy_annual_premium_groups
- policy_deductable_groups
- total_claim_amount
- umbrella_limit
- witnesses
categories_map:
  collision_type:
  - Side Collision
  - missing
  - Rear Collision
  - Front Collision
  property_damage:
  - 'YES'
  - missing
  - 'NO'
  police_report_available:
  - 'YES'
  - missing
  - 'NO'
  fraud_reported:
  - Y
  - N
  umbrella_limit:
  - 0
  - 5000000
  - 6000000
  - 4000000
  - 3000000
  - 8000000
  - 7000000
  - 9000000
  - 10000000
  - 2000000
  policy_deductable_groups:
  - 501-1000
  - 1501-2000
  - 0-500
  age_groups:
  - 46-50
  - 41-45
  - 26-30
  - 36-40
  - 31-35
  - 61-65
  - 21-25
  - 56-60
  - 51-55
  - 15-20
  policy_annual_premium_groups:
  - medium
  - high
  - low
  - very high
  - very low
  months_as_customer_groups:
  - 301-350
  - 201-250
  - 101-150
  - 251-300
  - 151-200
  - 0-50
  - 451-500
  - 51-100
  - 351-400
  - 401-450
  insured_hobbies:
  - others
  - chess
  - cross-fit
encoding_map:
  fraud_reported:
    N: 0
    Y: 1
  incident_severity:
    Trivial Damage: 0
    Minor Damage: 1
    Major Damage: 2
    Total Loss: 3
  policy_annual_premium_groups:
    very low: 0
    low: 1
    medium: 2
    high: 3
    very high: 4
  policy_deductable_groups:
    0-500: 0
    501-1000: 1
    1501-2000: 2
